// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.Data;

namespace Product.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20200520152322_Data-Seeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product.API.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Deskop",
                            InStock = 3,
                            Maker = "Acer",
                            Name = "PC",
                            Price = 14999f
                        },
                        new
                        {
                            ID = 2,
                            Description = "55 Tum",
                            InStock = 2,
                            Maker = "Philips",
                            Name = "TV",
                            Price = 8999f
                        },
                        new
                        {
                            ID = 3,
                            Description = "Iphone",
                            InStock = 5,
                            Maker = "Apple",
                            Name = "Headphones",
                            Price = 799f
                        },
                        new
                        {
                            ID = 4,
                            Description = "Gaming",
                            InStock = 4,
                            Maker = "Razor",
                            Name = "Keyboard",
                            Price = 1050f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
